-- ManualHub PostgreSQL Schema for Supabase

-- 1. Create manuals table
CREATE TABLE IF NOT EXISTS public.manuals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  project TEXT NOT NULL,
  revision TEXT NOT NULL,
  description TEXT,
  storage_path TEXT NOT NULL,
  current_version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 2. Create manual_versions table
CREATE TABLE IF NOT EXISTS public.manual_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  manual_id UUID NOT NULL REFERENCES public.manuals(id) ON DELETE CASCADE,
  revision TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 3. Create public_links table
CREATE TABLE IF NOT EXISTS public.public_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  manual_id UUID NOT NULL REFERENCES public.manuals(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ,
  password_hash TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 4. Create access_logs table
CREATE TABLE IF NOT EXISTS public.access_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  link_id UUID NOT NULL REFERENCES public.public_links(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('view', 'download')),
  ip TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Create Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_manuals_company ON public.manuals(company);
CREATE INDEX IF NOT EXISTS idx_manuals_project ON public.manuals(project);
CREATE INDEX IF NOT EXISTS idx_manual_versions_manual_id ON public.manual_versions(manual_id);
CREATE INDEX IF NOT EXISTS idx_public_links_token ON public.public_links(token);
CREATE INDEX IF NOT EXISTS idx_access_logs_link_id ON public.access_logs(link_id);

-- Storage Bucket Setup Instructions:
-- 1. Go to Supabase Storage -> Create Bucket named 'manuals'
-- 2. Toggle "Public bucket" to OFF (Keep it strictly PRIVATE).
-- 3. Access must be performed using Signed URLs generated by Supabase SDK.

-- Row Level Security (RLS) Policies
ALTER TABLE public.manuals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manual_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.public_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_logs ENABLE ROW LEVEL SECURITY;

-- Manuals Policies
CREATE POLICY "Authenticated users can select manuals" ON public.manuals FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert manuals" ON public.manuals FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update manuals" ON public.manuals FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete manuals" ON public.manuals FOR DELETE TO authenticated USING (true);
CREATE POLICY "Public users can view manuals attached to active valid public links" ON public.manuals FOR SELECT TO anon USING (
  EXISTS (
    SELECT 1 FROM public.public_links
    WHERE public_links.manual_id = public.manuals.id
    AND public_links.active = true
    AND (public_links.expires_at IS NULL OR public_links.expires_at > now())
  )
);

-- Manual Versions Policies
CREATE POLICY "Authenticated users can manage manual versions" ON public.manual_versions FOR ALL TO authenticated USING (true);
CREATE POLICY "Anon can view manual versions" ON public.manual_versions FOR SELECT TO anon USING (true);

-- Public Links Policies
CREATE POLICY "Authenticated users can manage public links" ON public.public_links FOR ALL TO authenticated USING (true);
CREATE POLICY "Anon can query active public link by token" ON public.public_links FOR SELECT TO anon USING (active = true);

-- Access Logs Policies
CREATE POLICY "Authenticated users can view access logs" ON public.access_logs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Anon can insert access log" ON public.access_logs FOR INSERT TO anon WITH CHECK (true);
